# Generated by Django 6.0.1 on 2026-03-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_onboarding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Free Trial'), ('trial_expired', 'Trial Expired'), ('active', 'Active (Paid)'), ('admin_granted', 'Admin Granted')], default='trial', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
