# Generated by Django 6.0.1 on 2026-03-03 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField(default=0)),
                ('instruction_text', models.TextField()),
                ('odoo_screen_target', models.CharField(blank=True, max_length=255)),
                ('action_type', models.CharField(choices=[('click', 'Click'), ('observe', 'Observe'), ('type', 'Type'), ('navigate', 'Navigate')], default='observe', max_length=20)),
                ('highlight_selector', models.CharField(blank=True, max_length=255)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='content.learningfile')),
            ],
            options={
                'ordering': ['file', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('explanation', models.TextField(blank=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='content.learningfile')),
            ],
            options={
                'ordering': ['file'],
            },
        ),
    ]
