# Generated by Django 6.0.1 on 2026-03-15 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_lessonslide_v2'),
        ('content', '0002_lessonstep_quizquestion'),
    ]

    operations = [
    ]
