# Generated by Django 6.0.1 on 2026-03-15 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_merge_20260316_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningsection',
            name='price_per_section',
        ),
    ]
