# Generated by Django 6.0.1 on 2026-03-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_price_per_section'),
        ('content', '0005_aiconversation'),
    ]

    operations = [
    ]
