# Generated by Django 6.0.1 on 2026-03-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_merge_20260317_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningfile',
            name='odoo_path',
            field=models.CharField(blank=True, default='', help_text="Odoo URL path for this lesson's practical task. e.g. /odoo/crm, /odoo/accounting/invoices", max_length=255),
        ),
        migrations.AddField(
            model_name='learningfile',
            name='odoo_task',
            field=models.TextField(blank=True, default='', help_text='Plain-text description of the practical task the user must complete in Odoo.'),
        ),
    ]
