# Generated by Django 6.0.1 on 2026-03-11 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        ('content', '0002_lessonstep_quizquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('total', models.IntegerField()),
                ('answers', models.JSONField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('learning_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='content.learningfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'learning_file')},
            },
        ),
    ]
