# Generated by Django 6.0.1 on 2026-03-15 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_lessonplan_v2'),
        ('assessment', '0002_userquizresult'),
    ]

    operations = [
    ]
