# Generated by Django 6.0.1 on 2026-03-28 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_merge_0002_lessonplan_v2_0002_userquizresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='chat_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_plans', to='assessment.assessment'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('active', 'Active'), ('completed', 'Completed')], default='pending_payment', max_length=25),
        ),
        migrations.AlterField(
            model_name='userquizresult',
            name='answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='userquizresult',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userquizresult',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
