# Generated by Django 6.0.1 on 2026-03-09 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('method', models.CharField(choices=[('card', 'Card (PayPal)'), ('cash', 'Cash'), ('cliq', 'CliQ')], max_length=10)),
                ('status', models.CharField(choices=[('not_paid', 'Not Paid'), ('pending_verification', 'Pending Verification'), ('paid', 'Paid')], default='not_paid', max_length=25)),
                ('paypal_order_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='assessment.studyplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
